<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ass2" nsURI="http://www.ntnu.no/tdt4250/ass2" nsPrefix="ass2">
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="BlackPiecesMustBeColorBlack WhitePiecesMustBeColorWhite AllChessPiecesMustBeOnUniqueSquares"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boardSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boardType" ordered="false"
        lowerBound="1" eType="#//BoardType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whitePieces" lowerBound="1"
        upperBound="16" eType="#//ChessPiece" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blackPieces" lowerBound="1"
        upperBound="16" eType="#//ChessPiece" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BoardType">
    <eLiterals name="Classic"/>
    <eLiterals name="FogOfWar" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="board" lowerBound="1" eType="#//Board"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lobby" lowerBound="1" eType="#//Lobby"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lobby">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PlayerOneAndPlayerTwoMustHaveOppositeColor"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lobbyID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playerOne" lowerBound="1"
        eType="#//Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playerTwo" lowerBound="1"
        eType="#//Player" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" lowerBound="1" eType="#//PlayerColor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pieces" upperBound="16"
        eType="#//ChessPiece" eOpposite="#//ChessPiece/player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChessPiece">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PieceColorMustBeSameAsPlayer"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pieceColor" lowerBound="1"
        eType="#//PlayerColor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player" eOpposite="#//Player/pieces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ability" eType="#//Ability"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moves" lowerBound="1" upperBound="-1"
        eType="#//MoveDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PlayerColor">
    <eLiterals name="WHITE"/>
    <eLiterals name="BLACK" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" lowerBound="1"
        eType="#//AbilityType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coolDownCounter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coolDownStartNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggerOnCaptureOnly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AbilityType">
    <eLiterals name="Passive"/>
    <eLiterals name="Active" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="IsMoveOnlyAndCanCaptureCantBothBeTrue CanCaptureAndIsCaptureOnlyMustBeSameValue"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moveX" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moveY" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInfinite" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canJump" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canCapture" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canMoveOnly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstMoveOnly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canCaptureOnly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
